### ISSUE TITLE
Update React Native?

### ISSUE THREAD

**Issue by slhck** [GeekyAnts/vue-native-cli#32]
This project creates a template with React Native version `0.59`.

Current latest is already 0.61.5.

What would need to be done to update this project? Or are there any dependencies related to `vue-native-core` that make this impossible?

**Comment by RishabhKarnad** [comment]
React Native can be upgraded as described in this doc:
https://reactnative.dev/docs/upgrading

We will also upgrade the RN version in the generated project to v0.63

There will be issues upgrading to v0.64 though, due to React 17 being used, which removes some deprecated methods used inside Vue Native
